Add notes for some final questions in arend, minor fixes
shd/tt2018-conspect pull request #51
Opened 2022-01-28 12:42 UTC by Jovvik

Содержательные изменения:
- Исправил синтаксис и ошибку в определении предикативного уровня
- Добавил гомотопический уровень
- Добавил мотивацию `\truncated` - избавление от конструктивности, с примерами (акси
- Добавил `\use \level`
- Добавил, что `\truncated` можно использовать не только для пропозиционального обрезания с примером - фактор-множество
- Добавил комбинатор K в базис BCKW, иначе можно было подумать, что BCW образуют базис, а это (мне кажется) не так

Все новое, что я добавил, есть в билетах 21 года, поэтому наверное это достаточно важно, чтобы включить в конспекты.

Мелочи:
- Добавил оператор `\with` для коньюнкции, чтобы были пробелы между оператором и операндами
- Заменил `\|` на `\mid` с той же целью
- Завернул код в моноширинный шрифт
- Исправил hbox overflow (#33, пункт 2):
	- В заголовке 6 лекции
	- В 5.3
	- В правилах вывода обобщенной ТС

2022-02-02 14:05 UTC, GoPavel commented
Образованились какие-то глупые конфликты, пофикси пожалуйста

2022-02-07 18:25 UTC, GoPavel commented
> Добавил оператор \with для коньюнкции, чтобы были пробелы между оператором и операндами
Заменил \| на \mid с той же целью

1. Это странно, кажется это использование DeclareMathOperator не по делу.
2. Где-то отсутствие пробелов вполне оправдано, потому что так формулы короче. А где это прям очень необходим можно вставить `~`.
3. Вы изменили не все вхождения `\&`
4. `\mid` -- это все таки другой знак, которые обозначает "такие что", а не логического или, в том месте на самом деле нужно заменить `|` на `\vee`

2022-02-07 19:21 UTC, GoPavel requested changes

2022-02-07 19:21 UTC, GoPavel commented on lection14.tex
> +Но мы можем с этим \ard{a} работать, не возвращая его:
Это не правда. Суть обрезания в том, что мы можем его элиминаровать (матчиться по ему) только есть у нас возвращаемый тип тоже обрезан или является утверждением. Что как раз правда в вашем примере, но дело в другом.

2022-02-07 19:21 UTC, GoPavel commented on lection14.tex
> +Таким образом мы можем избавляться от конструктивности. Например, мы можем определить аксиому выбора через \ard{TruncP}, которое аналогично \ard{\truncated} производит пропозициональное обрезание:
Надо написать,  что вообще такое TruncP, может написать его определение от [сюда](https://arend-lang.github.io/documentation/tutorial/PartII/hom-levels#truncated-data-propositional-truncation). И зачем он нужен: там вроде суть в том, что он позволяет интернализовать \truncated (это точно не надо писать) и написать тип `Trunc A`, что в HoTT аналогично `||A||`.

2022-02-07 19:21 UTC, GoPavel commented on lection14.tex
> +Таким образом мы можем избавляться от конструктивности. Например, мы можем определить аксиому выбора через \ard{TruncP}, которое аналогично \ard{\truncated} производит пропозициональное обрезание:
> Избавляться от конструктивности.

Сразу куча вопросов: а зачем нам от нее избавляться. А что как мы от нее в итоге избавляемся? А что у нас теперь классическая логика если мы избавились?

Лучше переформулировать

2022-02-07 19:21 UTC, GoPavel commented on lection14.tex
> +Эта функция недоказуема. Однако если определять аксиому выбора конструктивно, то она доказуема в ИИВ (и, следовательно, это не аксиома выбора)
```suggestion
Эта функция недоказуема (без других аксиом). Однако если определять аксиому выбора конструктивно, то она доказуема в ИИВ (и, следовательно, это не аксиома выбора):
```
Вообще я долго думал как это нормально сформулировать.. Проблема в том, что когда вы говорите "определить конструктивно" это и значит, что доказуемо в ИИВ. Тогда в чем смысл утверждения?

Я наверно понимаю посыл, что мы можем попробовать определить аксиому выбора без обрезания и без Prop и получим какое-то тривиальное утверждение, которое доказуемо, но в это надо или аккуратно сфомулировать или удалить этот абзац вообще, чтобы не вводить читателя в заблуждение.

2022-02-07 19:21 UTC, GoPavel commented on lection14.tex
> +С помощью \ard{\truncated} можно обрезать не только пропозиционально, но и до других универсумов. Например, можно построить фактор-множество над типом \ard{A} с отношением эквивалентности \ard{R}:
Тут как-то заметается под ковер, то что мы обрезаем до универума множеств и с помощью этого можем определить фактор-типы.

В идеале можно было как-то доказать этот факт, что мы действительно получим фактор-типа и нам не надо для них вводить отдельной конструкции, но это кажется overkill

2022-02-08 13:07 UTC, Jovvik commented
> 2. Где-то отсутствие пробелов вполне оправдано, потому что так формулы короче. А где это прям очень необходим можно вставить `~`.

Если не вставлять пробелы, то теряется согласованность с `\vee`, которое эти пробелы вставляет.

![image](https://user-images.githubusercontent.com/31628566/152991941-0f09541e-caff-49e3-9a39-1f3bc2ee2d2b.png)

Слева направо: `\vee`, `\&`, `\with`

2022-02-08 15:00 UTC, Jovvik commented on lection14.tex
> +Таким образом мы можем избавляться от конструктивности. Например, мы можем определить аксиому выбора через \ard{TruncP}, которое аналогично \ard{\truncated} производит пропозициональное обрезание:
> а зачем нам от нее избавляться.

На этот вопрос отвечает пример с аксиомой выбора.

> А что как мы от нее в итоге избавляемся?

На этот вопрос отвечает пример выше - то что мы не можем просто достать `a` из `Exists`

> А что у нас теперь классическая логика если мы избавились?

Я не очень понимаю, как написать так, чтобы такого вопроса не возникало. HOTT book, например, просто говорит, что мы можем создавать конструктивные и неконструктивные конструкции (стр. 122-123 про merely/purely)

2022-02-15 21:34 UTC, GoPavel approved these changes

2022-02-15 21:39 UTC, merged