add lection about F<:
shd/tt2018-conspect pull request #52
Opened 2022-01-29 14:31 UTC by Brat-vseznamus

2022-01-30 15:15 UTC, GoPavel requested changes
Спасибо за новый конспект, я постарался расписать некоторые моменты, которые мне кажется сделают материал более понятным.

Если какие-то пункт совсем не понятно как исправлять и что-то не понятно -- спрашивайте. В крайнем случае вмержим без них и создадим на это issue.

2022-01-30 15:15 UTC, GoPavel commented on lection15.tex
> +Мы рассматривали параметрический полиморфизм, как в системе типов Хиндли-Милнера. Но есть и другой подход --- ООП. Построим систему типов, которая описывает ООП, назовём её \(F_{<:}\). Определим отно
1. Не очень понятно "другой подход" к чему? К параметрическому полиморфизму или полиморфизму в целом (мне кажется второе).
2. Кажется фраза, что ООП -- это подход к полиморфизму не корректная. Это ведь более общий принцип. Поэтому лучше написать что-то типа:
```suggestion
Полиморфизм -- это способ предоставить единый интерфейс для множества различных реализаций. И обычно выделяют 3 вида полиморфизма: параметрический,  полиморфизм подтипов и ad-hoc полиморфизм.

В предыдущих главах была рассмотрена система типов Хиндли-Милнера, которая позволяет реализовать параметрический полиморфизм. Теперь давайте рассмотрим полиморфизм подтипов, который очень широко применятся в объектно-ориентированных языка программирования и фактически стал синонимом ООП. 
Мы построим систему типов с бинарным отношением \(<:\) на типах, которое будет значить если \(F <: G\) (\(F\) является подтипом \(G\)), то \(f : F\) может быть использована везде где используется \(g : G\). Назовем такую систему \(F_{<:}\). 
```

2022-01-30 15:15 UTC, GoPavel commented on lection15.tex
> +\subsection{Система типов \(F_{<:}\)}
В чем смысл использовать `\(` вместо `$` ?

2022-01-30 15:15 UTC, GoPavel commented on lection15.tex
> +    Рассмотрим направленный граф\footnote{На самом деле речь про категории, но не все знают, что это такое.} \(F\). Отображение графов\footnote{Функтор.} \(F \to G\) называется \textbf{ковариантным},
Может тогда и не надо про это писать пока?))

2022-01-30 15:15 UTC, GoPavel commented on lection15.tex
> +    Рассмотрим направленный граф\footnote{На самом деле речь про категории, но не все знают, что это такое.} \(F\). Отображение графов\footnote{Функтор.} \(F \to G\) называется \textbf{ковариантным},
Если ты хочешь сделать отсслыку к теоркат, то так и сделай.
Типа: на самом деле этот граф можно рассмотреть с точки зрения теорката, тогда F будет являться функтором

2022-01-30 15:15 UTC, GoPavel commented on lection15.tex
> +    Рассмотрим массив \(\texttt{[]}: * \to *\). Есть два метода "--- \texttt{get} и \texttt{set}. Так как один ковариантен, а другой контравариантен, получается, что если \(A <: B\), то и \(A\texttt{
```suggestion
    Рассмотрим массив \(\texttt{[]}: * \to *\). Есть два метода "--- \texttt{get} и \texttt{set}. Так как один ковариантен, а другой контравариантен, получается, что если \(A <: B\), то и \(A\texttt{[]} <: B\texttt{[]}\), и \(B\texttt{[]} <: A\texttt{[]}\), следовательно, массив инвариантен (ковариантен и контравариантен одновременое).
```
Ладно тут конечно вопрос определений, но кажется в твоих опредениях точно выполняются оба свойства и это называют или бивариантностью (вики) или инвариантностью (то, что я помню с лекций Георгия Александровича)

2022-01-30 15:15 UTC, GoPavel commented on lection15.tex
> +Введём символ \(S <: T\). Правила вывода:
```suggestion
Введём символ \(S <: T\) и правила вывода:
```

2022-01-30 15:15 UTC, GoPavel commented on lection15.tex
> +Некоторые новые правила (их на самом деле больше):
Нужно или указать их или пояснить почему они были не указаны или о чем они вообще. Не потом что лень, а например "также еще нужно добавить правила для того-то"

2022-01-30 15:15 UTC, GoPavel commented on lection15.tex
> +\subsection{Система типов \(F_{<:}^\omega\)}
Было бы не плохо написать какую-то мотивацию этого.
Хм, кажется надо написать какой-то туториал по тому как лучше писать конспект..
Просто, не смотря на то, что это коспект, а не книга, хотелось бы чтобы у читателя строилась в голове какая-то общая картина, а не просто набор определений и правил.

2022-01-30 15:15 UTC, GoPavel commented on lection15.tex
> +ООП получается из отношения \(<:\), экзистенциальных типов для инкапсуляции и структур:
Лучше как-то переформулировать учитывая замечания выше

2022-01-30 22:56 UTC, Brat-vseznamus commented on lection15.tex
> +\subsection{Система типов \(F_{<:}\)}
Ну концептуально понятно немного отличий, но в принципе это более современная штука, к ней прикручено пару полезных фич, а также более читаемые ошибки при компиляции. Вот еще [пару рассуждений](https://tex.stackexchange.com/questions/510/are-and-preferable-to-dollar-signs-for-math-mode) по этому поводу.

2022-01-30 23:30 UTC, Brat-vseznamus commented on lection15.tex
> +ООП получается из отношения \(<:\), экзистенциальных типов для инкапсуляции и структур:
А в каком формате переформатировать, а то не очень вяжется с замечанием выше?

2022-01-31 10:45 UTC, GoPavel commented on lection15.tex
> +ООП получается из отношения \(<:\), экзистенциальных типов для инкапсуляции и структур:
Я изначально имел ввиду свою замечание про ООП. Но может быть оно не очень релевантно.
Тут есть другая более важная проблема -- я ничего понял... я даже нотацию не понимаю.. это Аренд или что? что стоит вместо многоточия?
Странно все это как-то

2022-02-15 21:49 UTC, GoPavel commented on lection15.tex
> +Мы рассматривали параметрический полиморфизм, как в системе типов Хиндли-Милнера. Но есть и другой подход --- ООП. Построим систему типов, которая описывает ООП, назовём её \(F_{<:}\). Определим отно
Я не понимаю, что поменялось относительно этого треда.

P. S. Обычно треды резолвит тот, кто их открывал, убедишивсь, что они изменения действительно внесены и не требуют новых правок

2023-01-29 09:58 UTC, merged